### PR TITLE
Some optimization

### PR DESCRIPTION
**Pull request by PitPik**
I saw some optimization in your great work.
I made some test and realized some performance boost. This way it's smaller and probably also better to understand...
What do you think?

### CODE REVIEW

**Comment by AutoSponge** [comment]
I'm intrigued.  Do you have a link to the perf test or can you include it in the PR?

**Comment by PitPik** [comment]
@AutoSponge 
hi, I just realized that my approach doesn't pass your tests.
I just added `return ( depthCache[path] || _get ).call( this, path );` which makes it better... but still fails 18 out of 54. Not sure why yet (have to investigate).

About speed testing: I'm using just console.time('get');

**Comment by PitPik** [comment]
@AutoSponge 
added a `call( this )` to the first return ... down to 9 Fails...
Although I see the fails in test I would consider to fail anyhow. I don't know if `obj.` or `obj.null` should return anything else than `undefined`...

**Comment by PitPik** [comment]
The latest commit is even shorter now and passes all the tests...

**Comment by AutoSponge** [comment]
I haven't done the perf tests but the depthCache strategy in your PR will have a memory cost.  It may deserve its own parameter (e.g., `perfget.factory("memory first")` vs. `perfget.factory("speed first")`).  

When you expose depthCache in the PR, you find a function is created for every unique path:

```
depthCache
Object {a.b.c.d.e.f.g: function}a.b.c.d.e.f.g: function anonymous() {...
```

However, the approach in the master branch only creates a new function when the depth fn has not been memoized.  

```
depthCache
Object {7: function}7: function anonymous($0, $1, $2, $3, $4, $5, ...
```

A second call to `get('a.b.c.d.e.f.g')`, in both branches correctly returns the memoized function.  But in the PR branch, a call to `get('a.b.c.d.e.f.A')` would produce a new function while the master branch would return depth 7 again.

In a long lived application with high variance of paths, memory consumption would increase without a way to garbage collect it.  On the other hand, the current approach on increases memory footprint based on the variance of depth (which should stay at a maximum based on the app's data structure).

To construct a fair and objective perf test, it would need to test both cached and non-cached using same depth and varying depth paths.  That would produce 4 scores per implementation.  I suspect the needs of each application would need to be considered before choosing one.

However, I still feel the original implementation is the most general and least likely to cause a memory leak.

**Comment by PitPik** [comment]
You're perfectly right. I saw this from a different use-case point of view. We usually cache results 'manually' (which get garbage collected after all as the function looses its scope) so 'buffering' might make sense if you frequently look for the same things anyhow (as you wrote: based on the app's data structure... and also dependent on the amount of models you constantly deal with).
Your approach is way more general and definitely fast enough for general use.

I like your work very much. Keep up this spirit. There is much people can learn from your thoughts.
Thanks,
Peter

**Pull request closed without merging**
